NDefines.NDiplomacy.NUM_OF_GREAT_POWERS = 12
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -201				
NDefines.NDiplomacy.MIN_RELATIONS_TO_SUPPORT_INDEPENDENCE = -201
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.DISINHERIT_PRESTIGE_THRESHOLD = -25